// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace KLExtensions2022
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidPackageString = "c65c8ae7-d1a9-4ec6-a388-95df5120744c";
        public static Guid guidPackage = new Guid(guidPackageString);

        public const string guidPackageCmdSetString = "e2927997-aef0-4d0f-9392-a44d51a7b2c2";
        public static Guid guidPackageCmdSet = new Guid(guidPackageCmdSetString);

        public const string guidPackageSurroundWithCmdSetString = "060f8145-dd46-4faa-ab59-dfdbeea72dcc";
        public static Guid guidPackageSurroundWithCmdSet = new Guid(guidPackageSurroundWithCmdSetString);

        public const string guidPackageEditContextCmdSetString = "707f8641-5997-4761-a5f4-8194ea23f878";
        public static Guid guidPackageEditContextCmdSet = new Guid(guidPackageEditContextCmdSetString);

        public const string guidPackageCreateContextCmdSetString = "d9b63116-6852-4d49-8184-9d3c930148cb";
        public static Guid guidPackageCreateContextCmdSet = new Guid(guidPackageCreateContextCmdSetString);

        public const string guidImagesString = "d8bf0f90-62ba-4911-b5a7-3cac6baa0d50";
        public static Guid guidImages = new Guid(guidImagesString);

        public const string guidImages2String = "be09fee2-ef0c-4f6d-9d25-53c9d7d14dee";
        public static Guid guidImages2 = new Guid(guidImages2String);

        public const string guidImages3String = "9cf6d5c0-9768-421c-adfa-312091903d1a";
        public static Guid guidImages3 = new Guid(guidImages3String);

        public const string guidImages4String = "23aa0ada-6644-47fd-9bce-30c622e0da69";
        public static Guid guidImages4 = new Guid(guidImages4String);

        public const string guidImagesCreateString = "7d18561b-8b04-45e6-97b4-17fe6467bd43";
        public static Guid guidImagesCreate = new Guid(guidImagesCreateString);

        public const string guidImages1String = "879aaaf2-2865-4a25-9cb3-9649306a22dd";
        public static Guid guidImages1 = new Guid(guidImages1String);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int KLExtensionsMenuGroup = 0x1020;
        public const int KLExtensionsMenu = 0x1021;
        public const int RemoveCommentCommandId = 0x0100;
        public const int RemoveRegionsCommandId = 0x0200;
        public const int RemoveVarsCommandId = 0x0205;
        public const int AddPublicClassCommandId = 0x0210;
        public const int SetAllMethodsBreakpointsCommandId = 0x0220;
        public const int SurroundWithMenuGroup = 0x1020;
        public const int SurroundWithSubMenu = 0x0102;
        public const int SurroundWithBraceCommandId = 0x00FE;
        public const int SurroundWithParenthesisCommandId = 0x00FF;
        public const int SurroundWithDoubleQuotesCommandId = 0x0100;
        public const int SurroundWithIntStringCommandId = 0x0101;
        public const int SurroundWithTaskBracketCommandId = 0x0103;
        public const int SurroundWithItemsMenuGroup = 0x0104;
        public const int EditMenuGroup = 0x1022;
        public const int EditSubMenu = 0x0105;
        public const int EditItemsMenuGroup = 0x0106;
        public const int EditJoinLinesCommandId = 0x0107;
        public const int EditTitleCaseCommandId = 0x0108;
        public const int EditSentenceCaseCommandId = 0x010D;
        public const int EditLowerTitleCaseCommandId = 0x0109;
        public const int EditSelectWholeLineCommandId = 0x010A;
        public const int EditSortLinesAscCommandId = 0x010B;
        public const int EditSortLinesDescCommandId = 0x010C;
        public const int EditRemoveEmptyLinesCommandId = 0x011D;
        public const int SelectMenuGroup = 0x140A;
        public const int SelectSubMenu = 0x0231;
        public const int SelectItemsMenuGroup = 0x0232;
        public const int SelectMoveToFunctionCommandId = 0x0233;
        public const int InsertGuidCommandId = 0x0234;
        public const int DuplicateAndCommentCommandId = 0x0235;
        public const int InsertNullabilityCommandId = 0x0236;
        public const int CreateMenuGroup = 0x0140;
        public const int CreateSubMenu = 0x0141;
        public const int CreateItemsMenuGroup = 0x0142;
        public const int CreateObjectInitializerCommandId = 0x0143;
        public const int bmpPic1 = 0x0001;
        public const int bmpPic2 = 0x0002;
        public const int bmpPic3 = 0x0003;
        public const int bmpPic4 = 0x0004;
        public const int bmpPic5 = 0x0005;
        public const int bmpPic6 = 0x0006;
        public const int bmpPic7 = 0x0001;
        public const int bmpPic8 = 0x0002;
        public const int bmpPic9 = 0x0003;
        public const int bmpPic10 = 0x0004;
        public const int bmpPic11 = 0x0005;
        public const int bmpPic12 = 0x0006;
        public const int bmpPic13 = 0x0001;
        public const int bmpPic14 = 0x0002;
        public const int bmpPic15 = 0x0003;
        public const int bmpPic16 = 0x0004;
        public const int bmpPic17 = 0x0005;
        public const int bmpPic18 = 0x0001;
        public const int bmpPic19 = 0x0002;
        public const int bmpPic20 = 0x0003;
        public const int bmpObjInit = 0x0001;
        public const int bmpCollInit = 0x0002;
        public const int bmpPicSearch = 0x0003;
        public const int bmpPicX = 0x0004;
        public const int bmpPicArrows = 0x0005;
        public const int bmpPicStrikethrough = 0x0006;
    }
}